eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
  kafka: #Kafka Properties
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #Consumer side, we've to deserialize information to read that information.
      group-id: notificationId
    properties:
      spring:
        json:
          type:
            mapping: event:com.javaet.OrderPlacedEvent
            #should be same token with order-service mapping which is event.

server:
  port: 0