spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: time.sleep
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: inventory-service
  zipkin:
    base-url: http://localhost:9411
  sleuth: #Distributed Tracing
    sampler:
      probability: 1.0 #We want to send %100 of the request which we are receiving to our system to zipkin.

server:
  port: 8083
  #Comment:
    #I don't want to hard code the port number I want to run the service on a random port
    #At the time starting up spring boot will pick one random free port in your machine
    #and it will run the inventory service application on that port. No matter how many services
    #we run it's not a problem, it will try to take a free port and run the application.

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

  #Comment:
    #As these are eureka clients we have to add the properties of eureka server we have to provide the information
    #where we can find the eureka server.